# ==========================================
# ECO PIPELINE CONFIGURATIE BESTAND
# ==========================================

# 1. Mappen en Paden (Systeemconfiguratie)
MASTER_DIR="$HOME/Masterproef"
ECO_DIR="$HOME/eco-approx"
PROJ_DIR="$MASTER_DIR/project"
RAPIDWRIGHT_JAR="$MASTER_DIR/rapidwright-2024.1.1-standalone-lin64.jar"

SRC_FILE="$PROJ_DIR/Vivado/src/adder.v"
XDC_FILE="$PROJ_DIR/Vivado/constraints/timing_exp.xdc"
TOP_MODULE="top"
PART_NUMBER="xcu200-fsgd2104-2-e"


# 3. De Specifieke Aanpassing (ECO Parameters)
TARGET_LUT_B="f[61]_INST_0_i_4"
TARGET_NET="p_344_in"
TARGET_SLICE="SLICE_X63Y458"
