# ==========================================
# ECO PIPELINE CONFIGURATIE BESTAND
# ==========================================

# 1. Mappen en Paden (Systeemconfiguratie)
MASTER_DIR="$HOME/Masterproef"
ECO_DIR="$HOME/eco-approx"
PROJ_DIR="$HOME/Masterproef/project"

RAPIDWRIGHT_JAR="$MASTER_DIR/rapidwright-2024.1.1-standalone-lin64.jar"

SRC_FILE="$PROJ_DIR/Vivado/src/adder.v"
XDC_FILE="$PROJ_DIR/Vivado/constraints/timing_exp.xdc"
TOP_MODULE="top"
PART_NUMBER="xcu200-fsgd2104-2-e"


# 3. De Specifieke Aanpassing (ECO Parameters)
TARGET_LUT_B="f[61]_INST_0_i_4"
TARGET_NET="p_344_in"
TARGET_SLICE="SLICE_X63Y458"


CANDIDATES_JSON="/home/cian/Masterproef/project/results/run_lut_insertion/2026-04-21_17-34-57/reports_eco/lut_connections.json"
BASELINE_DCP="/home/cian/Masterproef/project/results/run_lut_insertion/2026-04-21_17-34-57/baseline_impl/checkpoints/post_route_timingexp.dcp"
# Theorie-term voor toegevoegde LUT delay
LUT_DELAY_PS="120.0"

# 1 = na elke technisch geslaagde iteratie wordt current_base.dcp vervangen
ADVANCE_ON_SUCCESS="0"

# 1 = alleen vervangen als delta_total_ps < 0
ADVANCE_ONLY_IF_IMPROVED="0"


MAX_CANDIDATES = "0"
ROUTE_MODE=timing
SOFT_PRESERVE=1
