# ==========================================
# ECO PIPELINE CONFIGURATIE BESTAND
# ==========================================

# 1. Mappen en Paden (Systeemconfiguratie)
MASTER_DIR="$HOME/Masterproef"
ECO_DIR="$HOME/eco-approx"
PROJ_DIR="$MASTER_DIR/project"
RAPIDWRIGHT_JAR="$MASTER_DIR/rapidwright-2023.1.0-standalone-lin64.jar"

SRC_FILE="$PROJ_DIR/Vivado/src/adder.v"
XDC_FILE="$PROJ_DIR/Vivado/constraints/timing_exp.xdc"
TOP_MODULE="top"
PART_NUMBER="xc7a200tfbg676-1"


# 3. De Specifieke Aanpassing (ECO Parameters)
TARGET_LUT_B="f[127]_INST_0_i_2"
TARGET_NET="cOut_OBUF_inst_i_4_n_0"
TARGET_SLICE="SLICE_X61Y128"
